In [2]:
# Creating NumPy Arrays

In [10]:
import numpy as np

# creating 1D array
arr1 = np.array([1,2,3,4,5])
print(f"1D array: \n{arr1}")

# creating 2D array
arr2 = np.array([[1,2,3],[5,6,7]])
print(f"\n2D array: \n{arr2}")

1D array: 
[1 2 3 4 5]

2D array: 
[[1 2 3]
 [5 6 7]]


In [20]:
# Ways of creating arrays

In [40]:
# Creating zero value arrays
arr3 = np.zeros((3,3))
print(f"Zero value array of 3x3: \n{arr3}")

# Creating ones value arrays
arr4 = np.ones((2,4))
print(f"\nOne value array of 2x4: \n{arr4}")

# Creating array of any similar value
arr5 = np.full((2,3),5)
print(f"\nArray of any similar value of any mxn: \n{arr5}")

# Creating array of indentity matrix
arr6 = np.eye(5)
print(f"\nArray of an identity matrix: \n{arr6}")

# Creating array of range function
arr7 = np.arange(1,10,2)
print(f"\nArray of a range function: \n{arr7}")

# Creating array of evenly spaced
arr8 = np.linspace(0,3,5)
print(f"\nArray of a evenly spaced: \n{arr8}")

Zero value array of 3x3: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

One value array of 2x4: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Array of any similar value of any mxn: 
[[5 5 5]
 [5 5 5]]

Array of an identity matrix: 
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Array of a range function: 
[1 3 5 7 9]

Array of a evenly spaced: 
[0.   0.75 1.5  2.25 3.  ]


In [44]:
# Checking array properties

In [48]:
# Type
print(f"Type of 1D array: {type(arr1)}")
print(f"Type of 2D array: {type(arr2)}")

# Shape
print(f"Shape of 1D array: {arr1.shape}")
print(f"Shape of 2D array: {arr2.shape}")

# Size
print(f"Size of 1D array: {arr1.size}")
print(f"Size of 2D array: {arr2.size}")

# Dimensions
print(f"Dimension of 1D array: {arr1.ndim}")
print(f"Dimension of 2D array: {arr2.ndim}")

# Data type
print(f"Data type of 1D array: {arr1.dtype}")
print(f"Data type of 2D array: {arr2.dtype}")

Type of 1D array: <class 'numpy.ndarray'>
Type of 2D array: <class 'numpy.ndarray'>
Shape of 1D array: (5,)
Shape of 2D array: (2, 3)
Size of 1D array: 5
Size of 2D array: 6
Dimension of 1D array: 1
Dimension of 2D array: 2
Data type of 1D array: int64
Data type of 2D array: int64


In [50]:
# Changing Data types

In [56]:
# Explicit type
arr = np.array([1,2,3], dtype=np.float32)
print(arr.dtype)
print(arr)

# Convert float to int
arr_int = arr.astype(np.int32)
print(arr_int)

float32
[1. 2. 3.]
[1 2 3]


In [69]:
# Reshaping and flatting arrays
arr = np.array([[1,2,3],[4,5,6]])
print(f"Shape of original array: {arr.shape}")
print(f"Original array: \n{arr}")

reshaped = arr.reshape((3,2))
print(f"\nShape of reshaped array: {reshaped.shape}")
print(f"Reshaped array: \n{reshaped}")

flattened = arr.flatten()
print(f"\nFlattened array: \n{flattened}")

Shape of original array: (2, 3)
Original array: 
[[1 2 3]
 [4 5 6]]

Shape of reshaped array: (3, 2)
Reshaped array: 
[[1 2]
 [3 4]
 [5 6]]

Flattened array: 
[1 2 3 4 5 6]
