In [6]:
# Indexing and slicing

In [16]:
import numpy as np

arr = np.array([10,20,30,40,50])

In [17]:
# Indexing
print(arr[0])
print(arr[-1])

10
50


In [18]:
# Slicing
print(arr[0:2])
print(arr[:3])
print(arr[::2])

[10 20]
[10 20 30]
[10 30 50]


In [20]:
sliced = arr[1:4]
sliced[0] = 999
print(arr)

[ 10 999  30  40  50]


In [ ]:
# Fancy indexing
idx = [0,2,4]
print