In [1]:
# Understanding Axis in numpy

In [2]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(f"Matrix of 3x3 : \n{arr}")

# Summing along axis
print(f"\nSum of matrix along with axis 0 which indicates to the row & do the sum through column-wise: \n{np.sum(arr, axis=0)}")
print(f"\nSum of matrix along with axis 1 which indicates to the column & do the sum through row-wise: \n{np.sum(arr, axis=1)}")

Matrix of 3x3 : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum of matrix along with axis 0 which indicates to the row & do the sum through column-wise: 
[12 15 18]

Sum of matrix along with axis 1 which indicates to the column & do the sum through row-wise: 
[ 6 15 24]


In [3]:
# Indexing in multidimensional array
print(f"Value of an array through the row and column wise place value, row indicates the first index and column indicates the second index: {arr[0,2]}")
print(f"Value of an array through the row and column wise place value, row indicates the first index and column indicates the second index: {arr[2,2]}")

# Through slicing
print(f"Value of an array through slicing of row and column values: \n{arr[0:2, 1:3]}")

Value of an array through the row and column wise place value, row indicates the first index and column indicates the second index: 3
Value of an array through the row and column wise place value, row indicates the first index and column indicates the second index: 9
Value of an array through slicing of row and column values: 
[[2 3]
 [5 6]]


In [4]:
# Indexing in 3D arrays
arr3D = np.array([[[1,2,3],[4,5,6]],
                  [[7,8,9],[10,11,12]]])
print(f"Shape of 3D array: {arr3D.shape}")
print(f"Result of 3D array: \n{arr3D}")

# accessing in 3d array
print(f"\nValue of 3d array through its index value: {arr3D[0,1,2]}")   # Here 0 shows the first sheet, 1 shows the second row, 2 shows the third column
print(f"\nGet the first row from the both sheets: {arr3D[:,0,:]}")

Shape of 3D array: (2, 2, 3)
Result of 3D array: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Value of 3d array through its index value: 6

Get the first row from the both sheets: [[1 2 3]
 [7 8 9]]


In [5]:
# Selecting data along axis

In [6]:
# Get all rows of the first column
first_cols = arr[:,0]
print(f"Get all rows of the first column of a matrix: {first_cols}")

# Get the first row from each "sheet" in a 3D array
first_rows = arr3D[:,0,:]
print(f"\nGet the first row from each 'sheet' in a 3D array matrix: \n{first_rows}")

Get all rows of the first column of a matrix: [1 4 7]

Get the first row from each 'sheet' in a 3D array matrix: 
[[1 2 3]
 [7 8 9]]


In [9]:
# Changing data along with axis

# Replace all elements in coulmn 1 with 0
arr[:,1] = 0
print(f"change all element of a particular coulmn and row of an array matrix: \n{arr}")

change all element of a particular coulmn and row of an array matrix: 
[[1 0 3]
 [4 0 6]
 [7 0 9]]
