In [9]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


In [8]:
# Changing data types
arr_float = arr.astype(np.float64)
print(arr_float)
print(arr_float.dtype)

[1. 2. 3. 4. 5.]
float64


In [14]:
# Downcasting to save memory
arr_large = np.array([10000000, 20000000, 30000000], dtype = np.int64)
arr_small = arr_large.astype(np.int32)
print(arr_small)
print(arr_small.dtype)
print(arr_large.dtype)

[10000000 20000000 30000000]
int32
int64


In [16]:
# Memory usage
arr_int64 = np.array([1,2,3], dtype = np.int64)
arr_int32 = np.array([1,2,3], dtype = np.int32)

print(arr_int64.nbytes)
print(arr_int32.nbytes)

24
12


In [20]:
# String array data type
arr = np.array(['apple', 'banana', 'cheery'], dtype='U10')  # unicode string array
print(arr)

['apple' 'banana' 'cheery']


In [21]:
# Complex numbers data type
arr = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype = 'complex128')
print(arr)

[1.+2.j 3.+4.j 5.+6.j]
