In [6]:
# Looping over arrays in python

import numpy as np

arr = np.array([1,2,3,4,5])
result = []
# Using a loop to square each element
for num in arr:
    result.append(num**2)

print(result)

[np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25)]


In [7]:
# Vectorized operation
result = arr**2
print(result)

[ 1  4  9 16 25]


In [9]:
# Broadcasting with scalar
result = arr + 10
print(result)

[11 12 13 14 15]


In [10]:
# Broadcasting with two arrays
arr1 = np.array([1,2,3])
arr2 = np.array([10,20,30])
result = arr1 + arr2
print(result)

[11 22 33]


In [12]:
# Broadcasting a 2D array and a 1D array
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([1,2,3])
result = arr1 + arr2
print(result)

[[2 4 6]
 [5 7 9]]


In [13]:
# Normalizing data using broadcasting

In [16]:
# Simulating a dataset
data = np.array([[10,20,30],
                 [15,25,35],
                 [20,30,40],
                 [25,35,45],
                 [30,40,50]])

# calculating mean and standard deviation for each feature
mean = data.mean(axis=0)
std = data.std(axis=0)
print(f"Mean of this dataset is: {mean}")
print(f"Standstd)
# Normalizing the data using broadcasting
normalized_data = (data-mean)/std

print(normalized_data)

[20. 30. 40.]
[7.07106781 7.07106781 7.07106781]
[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
